version: "3.7"
services:
  app:
    build:
      args:
        user: bob
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: sunergetics
    container_name: sunergetics-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - sunergetics

  db:
    image: mysql:5.7
    container_name: sunergetics-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sunergetics
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_PASSWORD: secret
      MYSQL_USER: bob
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - sunergetics

  nginx:
    image: nginx:alpine
    container_name: sunergetics-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - sunergetics

networks:
  sunergetics:
    driver: bridge
